I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 605, in script
    $ inv.add_item(bandages)
  File "game/script.rpy", line 605, in <module>
    $ inv.add_item(bandages)
NameError: name 'bandages' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 605, in script
    $ inv.add_item(bandages)
  File "C:\Users\Ryan\Documents\Renpy\renpy-8.2.0-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Ryan\Documents\Renpy\renpy-8.2.0-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 605, in <module>
    $ inv.add_item(bandages)
NameError: name 'bandages' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
Derleth Manor 1.0
Sat Mar 23 11:10:40 2024
